/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ImplementorService } from "../implementor.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ImplementorCreateInput } from "./ImplementorCreateInput";
import { Implementor } from "./Implementor";
import { ImplementorFindManyArgs } from "./ImplementorFindManyArgs";
import { ImplementorWhereUniqueInput } from "./ImplementorWhereUniqueInput";
import { ImplementorUpdateInput } from "./ImplementorUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ImplementorControllerBase {
  constructor(
    protected readonly service: ImplementorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Implementor })
  @nestAccessControl.UseRoles({
    resource: "Implementor",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createImplementor(
    @common.Body() data: ImplementorCreateInput
  ): Promise<Implementor> {
    return await this.service.createImplementor({
      data: data,
      select: {
        availability: true,
        communicationChannels: true,
        compensation: true,
        createdAt: true,
        email: true,
        expectations: true,
        experience: true,
        fullName: true,
        id: true,
        onlineProfiles: true,
        phone: true,
        portfolio: true,
        projectPreferences: true,
        skills: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Implementor] })
  @ApiNestedQuery(ImplementorFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Implementor",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async implementors(@common.Req() request: Request): Promise<Implementor[]> {
    const args = plainToClass(ImplementorFindManyArgs, request.query);
    return this.service.implementors({
      ...args,
      select: {
        availability: true,
        communicationChannels: true,
        compensation: true,
        createdAt: true,
        email: true,
        expectations: true,
        experience: true,
        fullName: true,
        id: true,
        onlineProfiles: true,
        phone: true,
        portfolio: true,
        projectPreferences: true,
        skills: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Implementor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Implementor",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async implementor(
    @common.Param() params: ImplementorWhereUniqueInput
  ): Promise<Implementor | null> {
    const result = await this.service.implementor({
      where: params,
      select: {
        availability: true,
        communicationChannels: true,
        compensation: true,
        createdAt: true,
        email: true,
        expectations: true,
        experience: true,
        fullName: true,
        id: true,
        onlineProfiles: true,
        phone: true,
        portfolio: true,
        projectPreferences: true,
        skills: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Implementor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Implementor",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateImplementor(
    @common.Param() params: ImplementorWhereUniqueInput,
    @common.Body() data: ImplementorUpdateInput
  ): Promise<Implementor | null> {
    try {
      return await this.service.updateImplementor({
        where: params,
        data: data,
        select: {
          availability: true,
          communicationChannels: true,
          compensation: true,
          createdAt: true,
          email: true,
          expectations: true,
          experience: true,
          fullName: true,
          id: true,
          onlineProfiles: true,
          phone: true,
          portfolio: true,
          projectPreferences: true,
          skills: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Implementor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Implementor",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteImplementor(
    @common.Param() params: ImplementorWhereUniqueInput
  ): Promise<Implementor | null> {
    try {
      return await this.service.deleteImplementor({
        where: params,
        select: {
          availability: true,
          communicationChannels: true,
          compensation: true,
          createdAt: true,
          email: true,
          expectations: true,
          experience: true,
          fullName: true,
          id: true,
          onlineProfiles: true,
          phone: true,
          portfolio: true,
          projectPreferences: true,
          skills: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
