/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { InnovatorService } from "../innovator.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { InnovatorCreateInput } from "./InnovatorCreateInput";
import { Innovator } from "./Innovator";
import { InnovatorFindManyArgs } from "./InnovatorFindManyArgs";
import { InnovatorWhereUniqueInput } from "./InnovatorWhereUniqueInput";
import { InnovatorUpdateInput } from "./InnovatorUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class InnovatorControllerBase {
  constructor(
    protected readonly service: InnovatorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Innovator })
  @nestAccessControl.UseRoles({
    resource: "Innovator",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createInnovator(
    @common.Body() data: InnovatorCreateInput
  ): Promise<Innovator> {
    return await this.service.createInnovator({
      data: data,
      select: {
        createdAt: true,
        id: true,
        projectDescription: true,
        projectName: true,
        skillsNeeded: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Innovator] })
  @ApiNestedQuery(InnovatorFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Innovator",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async innovators(@common.Req() request: Request): Promise<Innovator[]> {
    const args = plainToClass(InnovatorFindManyArgs, request.query);
    return this.service.innovators({
      ...args,
      select: {
        createdAt: true,
        id: true,
        projectDescription: true,
        projectName: true,
        skillsNeeded: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Innovator })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Innovator",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async innovator(
    @common.Param() params: InnovatorWhereUniqueInput
  ): Promise<Innovator | null> {
    const result = await this.service.innovator({
      where: params,
      select: {
        createdAt: true,
        id: true,
        projectDescription: true,
        projectName: true,
        skillsNeeded: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Innovator })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Innovator",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateInnovator(
    @common.Param() params: InnovatorWhereUniqueInput,
    @common.Body() data: InnovatorUpdateInput
  ): Promise<Innovator | null> {
    try {
      return await this.service.updateInnovator({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          projectDescription: true,
          projectName: true,
          skillsNeeded: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Innovator })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Innovator",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteInnovator(
    @common.Param() params: InnovatorWhereUniqueInput
  ): Promise<Innovator | null> {
    try {
      return await this.service.deleteInnovator({
        where: params,
        select: {
          createdAt: true,
          id: true,
          projectDescription: true,
          projectName: true,
          skillsNeeded: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
